Iter13
leonf08/metrics-yp pull request #13
Opened 2023-10-02 10:24 UTC by leonf08

2023-10-08 17:55 UTC, Bazys requested changes
переделай `Server struct` так что бы а ней не было члена `fileStorage *storage.FileStorage`
она должна принимать интерфейс `Repository` и всё. а в зависимости от параметров запуска, туда подставляем одну из трех струтур.

2023-10-08 17:55 UTC, Bazys commented on internal/storage/postgres.go
> +		CREATE TABLE IF NOT EXISTS metrics(
Давай будем взрослыми мальчиками и воспользуемся миграторами. В ГО их несколько есть.

2023-10-08 17:55 UTC, Bazys commented on internal/storage/postgres.go
> +		_, err := db.db.ExecContext(ctx, queryStr)
Согласись что db.db некрасиво выглядит.
Давай `type PostgresDB struct` назовем как то вроде PGStorage, по аналогии с FileStorage.

2023-10-08 17:55 UTC, Bazys commented on internal/server/httpserver/server.go
> +	fileStorage *storage.FileStorage
отличное начало с интерфейсом репозиторя для storage.
у тебя д.б. 3 структуры удовлетворяющих этому интерфейсу и в зависимости от  параметров, ты инициализируешь ту или другую структуру и передаешь, как удовлетворяющую данному интерфейсу и тогда не нужна будет 42 строка - fileStorage *storage.FileStorage

2023-10-09 15:29 UTC, leonf08 commented on internal/storage/postgres.go
> +		CREATE TABLE IF NOT EXISTS metrics(
реализовал миграцию

2023-10-09 15:30 UTC, leonf08 commented on internal/storage/postgres.go
> +		_, err := db.db.ExecContext(ctx, queryStr)
подправил на PGStorage, receiver теперь st, сама запись st.db

2023-10-09 15:31 UTC, leonf08 commented on internal/server/httpserver/server.go
> +	fileStorage *storage.FileStorage
fileStorage привязал к in-memory storage, так как они работают в связке, по месту использования fileStorage делаю type assertion проверку

2023-10-09 18:45 UTC, Bazys approved these changes
вот так выглядит более гармонично

2023-10-14 17:30 UTC, merged