Iter5
leonf08/metrics-yp pull request #5
Opened 2023-08-10 14:33 UTC by leonf08

2023-08-11 10:07 UTC, Bazys requested changes

2023-08-11 10:07 UTC, Bazys commented on cmd/agent/flags.go
> +	addr string
а зачем глобальные переменные?

2023-08-11 10:07 UTC, Bazys commented on cmd/agent/flags.go
> +	flag.StringVar(&addr, "a", "localhost:8080", "Host address of the server")
они могут тут быть локальными и возвращается заполненная структура.

2023-08-11 12:15 UTC, leonf08 commented on cmd/agent/flags.go
> +	addr string
исправлено

2023-08-11 12:16 UTC, leonf08 commented on cmd/agent/flags.go
> +	flag.StringVar(&addr, "a", "localhost:8080", "Host address of the server")
исправлено в соответствии с замечанием

2023-08-12 09:46 UTC, Bazys approved these changes

2023-08-12 13:09 UTC, merged