Iter9
leonf08/metrics-yp pull request #9
Opened 2023-09-06 08:38 UTC by leonf08

2023-09-10 08:55 UTC, Bazys requested changes
есть несколько вопросов, в большинстве не критичные, но хотелось, что бы ты переделал как минимум следующее:
- NewRequestWithContext
- магическое число 20
- проверка на ошибку в тикере
Так же, настрой gofmt или goimports или gofumpt на форматирование кода перед коммитом. Можно использовать гит хуки, либо в IDE при каждом сохранении файла запускать форматер.
А в целом проделана очень большая и серьезная работа по структуре проекта, он стал логически более понятным и правильным.

2023-09-10 08:55 UTC, Bazys commented on internal/app/agentapp/agent.go
> +		currentTime := time.Now()
попробуй следующий раз переделать реализацию через тикер
https://pkg.go.dev/time#NewTicker 
тем более ты уже такое использовал в своем коде

2023-09-10 08:55 UTC, Bazys commented on internal/app/agentapp/agent.go
> +func sendMetricJSON(cl *http.Client, st storage.Repository, log logger.Logger, url string) {
а может ее сделать методом структуры? не надо будет передавать кучу параметров?

2023-09-10 08:55 UTC, Bazys commented on internal/app/agentapp/agent.go
> +	config  *agentconf.Config
а не думал и логер сделать членом структуры? не надо будет больше его отдельно передавать во все методы? и точно будешь знать на каком уровне установлено логирования на всё твое приложение

2023-09-10 08:55 UTC, Bazys commented on internal/app/agentapp/agent.go
> +// func sendMetric(cl *http.Client, st storage.Repository, log logger.Logger, req string) {
закомментированный код в PR в мастер ветку - муветон. у тебя всегда есть история в гит

2023-09-10 08:55 UTC, Bazys commented on internal/app/agentapp/app.go
> +	client := &http.Client{Timeout: 20*time.Second}
почему именно 20? почему магическое число в коде?
для начала вынеси в константу в заголовки файла, а в реалиях такое выносят в конфиг, так как внешний сервис со временем может деградировать и начать не укладываться в 20 секунд

2023-09-10 08:55 UTC, Bazys commented on internal/app/agentapp/agent.go
> +		req, err := http.NewRequest(http.MethodPost, url, &buf)
рекомендую использовать NewRequestWithContext
а контекст делать с таймаутом (в те же магические 20 секунд)

2023-09-10 08:55 UTC, Bazys commented on internal/app/serverapp/app.go
> +						server.Saver.SaveMetrics()
ты тут на ошибку не проверяешь, а если сохранение прошло не удачно?

2023-09-10 08:55 UTC, Bazys commented on internal/app/serverapp/app.go
> +						server.Saver.SaveMetrics()
тут тоже, если не удалось сохранить, то точно должны выходить с 0 кодом?

2023-09-10 21:38 UTC, leonf08 commented on internal/app/agentapp/agent.go
> +		req, err := http.NewRequest(http.MethodPost, url, &buf)
done

2023-09-10 21:40 UTC, leonf08 commented on internal/app/agentapp/app.go
> +	client := &http.Client{Timeout: 20*time.Second}
добавил NewRequestWithContext, но пока убрал таймаут у клиента
по какой-то причине из-за него валятся тесты второго инкремента

2023-09-13 06:00 UTC, Bazys approved these changes

2023-09-13 07:58 UTC, merged